---
engines:
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .jsx
    channel: "eslint-4"
    checks:
      import/no-duplicates:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
      import/no-named-as-default-member:
        enabled: false
      import/no-unresolved:
        enabled: false
  stylelint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.scss"
exclude_paths:
  - coverage/**/*
  - dist/**/*
  - documentation/**/*
  - node_modules/**/*
